### ISSUE TITLE
Flaw in GetRandomString/GetRandomNumber

### ISSUE THREAD

**Issue by sdrapkin** [bitbeans/StreamCryptor#14]
This logic has been **audited** by Cure53 and the only flaw they identified was an off-by-1 reduction which has no meaningful impact (fixed by author). All is good, right?

GetRandomNumber() uses crng to seed Random(), and then uses Random() to generate a sequence of numbers (characters in GetRandomString) of a given length. Random() is a deterministic rng with a 32-bit seed. The 2^32 starting sequences produced by every possible Random() seed can be easily generated, practically stored, and used as a dictionary.

My understanding is that GetRandomString() is primarily used to generate unique filenames. The silliness of this implementation is also due to inadequate knowledge of .NET (this project targets .NET 4.5). The author should use Path.GetRandomFileName() which does it right.

**Comment by bitbeans** [comment]
@sdrapkin thank you for reporting this, and for checking the code!

This was already reported by @paragonie-scott per email.

```Path.GetRandomFileName()``` uses the complete Base32 charset right? 
At the current implementation i excluded some of characters: (1,l,L,i,I).
It also adds some random file extension? If i cut and replace them with for example .sccef there are only 8 random characters left (currently there are 11).

I already pulled ```GetRandomNumber()``` to libsodium-net (http://bitbeans.gitbooks.io/libsodium-net/content/generating_random_data/index.html) and i`am just waiting for the next stable release.

I'm open to suggestions.

**Comment by sdrapkin** [comment]
I suggest the below approach. It uses a custom character map (your own), provides adequate uniformity (you don't need expensive non-deterministic-time perfect uniformity for every character), has zero dependencies on libraries beyond your control (not covered by your audit) and does not incur unmanaged interop costs. Sprinkle argument/bounds checking as desired.

```c#
public static string GetRandomString(int length)
{		
	byte[] randomBytes = new byte[sizeof(ulong) * length];
	_csrng.GetBytes(randomBytes);
	char[] resultChars = new char[length];
	ulong randomUlong;
	
	for (int i = 0; i < resultChars.Length; ++i)
	{
		randomUlong = BitConverter.ToUInt64(randomBytes, sizeof(ulong)*i);
		resultChars[i] = _charMap[randomUlong % _charMapLength];
	}
	return new string(resultChars);
}

static readonly RNGCryptoServiceProvider _csrng = new RNGCryptoServiceProvider();
static readonly char[] _charMap = new char[]
{
	'0', '2', '3', '4', '5', '6', '8', '9',
	'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'j', 'k', 'm', 'n', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
	'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'J', 'K', 'L', 'M', 'N', 'P', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'
};
static readonly uint _charMapLength = (uint)_charMap.Length;

**Comment by paragonie-scott** [comment]
So, reducing a random byte (0-255) modulo any value that is not a multiple of 2^n is going to introduce bias in the output.

For example, base-58 will significantly be more biased towards the values 0-23.

> has zero dependencies on libraries beyond your control (not covered by your audit)

Since StreamCryptor depends on libsodium anyway, using `Sodium.SodiumCore.GetRandomNumber(58)` is the correct solution. I've provided a stopgap to provide secure, unbiased random strings until the next libsodium release in another project. If @bitbeans would like, I can send a PR to implement the same stopgap here.

**Comment by sdrapkin** [comment]
@paragonie-scott : "base-58 will significantly be more biased towards the values 0-23." Wrong. First of all, the char map is 54 chars, not 58. More importantly, the random number is 2^64. The statistical bias will be insignificant due to ~341 quadrillion full modulo ranges. The use of ulong is very much intentional.

"Since StreamCryptor depends on [external library] anyway, using [external library] is the correct solution". Wrong. Using an external library is an additional risk, which might be justified for crucial or trusted functionality available **only** in external library. CSRNG is not one of them. Nor are uniform random integers (not needed by StreamCryptor). Using an external library for what GetRandomString() is intended to do would be an admission of inability to do it right internally, and an unjustified transfer of risk.

**Comment by paragonie-scott** [comment]
>  Wrong. First of all, the char map is 54 chars, not 58.

If it were 2, 4, 8, 16, 32, 64, 128, or 256, then it could result in an unbiased distribution. 54 suffers from the same condition as 58.

> More importantly, the random number is 2^64.

This does not remove the existence of the bias.

```js
var ANY_POWER_OF_2 = 65536; // replace this with any power of 2
var rangeLength = 54;

var ranges = new Array(rangeLength);
for (var i = 0; i < rangeLength; ++i) {
    ranges[i] = 0;
}

for (i = 0; i < ANY_POWER_OF_2; ++i) {
    ranges[i % rangeLength]++;
}
```

I guarantee you that `ranges` will not be distributed evenly.

> Using an external library is an additional risk, which might be justified for crucial or trusted functionality available only in external library.

An additional risk of what?

> Using an external library for what GetRandomString() is intended to do would be an admission of inability to do it right internally, and an unjustified transfer of risk.

Risk of what?

**Comment by paragonie-scott** [comment]
Epilogue:

![Biased](http://i.imgur.com/56TyMo3.png)

**Comment by jedisct1** [comment]
I don't disagree with the fact that the bias has little practical implications, but getting rid of it of it is trivial, so there are no reasons to recommend using a flawed way to fix a flaw.

The project already heavily depends on libsodium.net, so recommending to avoid using it for this specific function, and reimplement it in a less secure way instead makes little sense.

```csharp
    do {
        randomUlong = BitConverter.ToUInt16(randomBytes, sizeof(ulong)*i) % 64;
    } while (randomUlong > 53);
```

is all it would take to avoid the bias.

But it wouldn't make any difference with calling `Sodium.SodiumCore.GetRandomNumber()`.

**Comment by sdrapkin** [comment]
This is a classic example of how easy (and tempting) it is to miss the forest for the trees. The "*must* produce uniformly random values" is a self-imposed restriction/requirement, often created by [group-think](https://en.wikipedia.org/wiki/Groupthink). This self-imposed requirement is entirely made up, and has no rational basis other than "man, it feels good to be uniformly random!".

GetRandomString() should've been called GetRandomFileName() because that's precisely what it does - or, rather, attempts to do. It is used in exactly 2 places in the code for identical purpose: to generate a new filename that didn't exist before. It is called both times with "11" as the desired length.

The astute might realize that the only goal is to generate the necessary amount of entropy of entire output - not ensure uniform randomness of individual characters. Ensuring uniform randomness is not free, and comes at a cost of slower runtime, non-deterministic runtime, and additional complexity (even when shifted to external lib) - with essentially zero gain to show for it.

Before everyone grabs their torches and pitchforks and continues to fight the righteous perfect-randomness war, ponder this:

The current implementation generates a new, hopefully non-colliding (ie. unique enough) 11-character filename (ignoring fixed extensions) out of 54-character map, consisting of 23 upper+lower chars and 8 digits. As you brand the statistically insignificant 2^64%[small-range] as "impure",  "weak", and "unworthy", note that Windows filesystems are case-insensitive and the 54-char range is actually 31 chars. How's that for statistically significant?

**Comment by paragonie-scott** [comment]
> This is a classic example of how easy (and tempting) it is to miss the forest for the trees. The "must produce uniformly random values" is a self-imposed restriction/requirement, often created by group-think. 

You're essentially accusing, among others, @jedisct1 (who is the person who created libsodium to make NaCl's cryptography more accessible to developers) of group-think. 

For the record, this is the same person who has an established history politely and kindly sniped holes in the weak spots of every bad suggestion I've ever made. If anyone is *not* susceptible to groupthink, it would be him.

You're making an ass of yourself with remarks like this.

> This self-imposed requirement is entirely made up, and has no rational basis other than "man, it feels good to be uniformly random!".

Except, this exact issue was one (of many) that led CryptoCat to be [decryptable](http://tobtu.com/decryptocat.php).

I'll accept that the circumstances and use-cases were totally different, but if we're going to fix this, why should we accept a RNG fix that **biases outputs towards specific values** when we can avoid it trivially?

> GetRandomString() should've been called GetRandomFileName() because that's precisely what it does - or, rather, attempts to do. It is used in exactly 2 places in the code for identical purpose: to generate a new filename that didn't exist before. It is called both times with "11" as the desired length.

That's up to @bitbeans to decide; it's his library.

> Ensuring uniform randomness is not free, and comes at a cost of slower runtime, non-deterministic runtime, and additional complexity (even when shifted to external lib) - with essentially zero gain to show for it.

Except this library explicitly depends on libsodium.net and protobuf, so having libsodium provide the RNG that's used to generate random strings *makes sense*. How did that saying go? **Don't roll your own crypto.** Same concept applies with RNGs.

I can almost guarantee you that this "slower runtime"/penalty for uniform randomness will **never** be the bottleneck of any real-world application. If you disagree, please provide benchmarks.

Keep in mind when you write statements like, "`even when shifted to external lib`", that the goal of this project is not to offer random string generation logic for arbitrary use-cases. Its goal is to provide a streaming encryption library built with libsodium and protobuf.

Also, **`essentially zero !== zero`**.

> Before everyone grabs their torches and pitchforks and continues to fight the righteous perfect-randomness war, ponder this:

Is this tone *really* necessary?

>  As you brand the statistically insignificant 2^64%[small-range] as "impure", "weak", and "unworthy"

Nobody used the words impure or unworthy except you.

> Windows filesystems are case-insensitive and the 54-char range is actually 31 chars. How's that for statistically significant?

This is a fair criticism.

What say you about being exclusively lowercase, @bitbeans?

For reference, `lg(54^11)` is about `63.3`, so an equivalently random name in base31 would be about 13 characters (`lg(31^13)` is about `64.4`).

**Comment by adamcaudill** [comment]
I'll throw my $0.02 into this - though quite frankly I think this is a non-issue, and I'd close this issue if I was @bitbeans. This isn't a security issue, so I would say that it isn't worth the effort being put into it. But that's just me...

> "Since StreamCryptor depends on [external library] anyway, using [external library] is the correct solution". Wrong. Using an external library is an additional risk, which might be justified for crucial or trusted functionality available only in external library. CSPRNG is not one of them.

There is so much I disagree with here. So, @sdrapkin, when you write something that needs a RNG, do you implement one yourself? Do you rip the code and include it in your application? Use .NET - that CSPRNG is in an external library. Both `libsodium` and .NET are just wrappers. Using `GetRandomFileName()` is just as external as something from `libsodium` from a risk perspective - though using something from `libsodium` may present less of a risk thanks to the ease of auditing.

> The "must produce uniformly random values" is a self-imposed restriction/requirement, often created by group-think. This self-imposed requirement is entirely made up

Yes, self-imposed requirement - libraries often have requirements that they try to live up to, even if not entirely necessary. That's the great thing about running a project like this, you can set your design goals and build to them. If you dislike the design goals, perhaps the best thing to do would be to design a competing library.

As to the comment on groupthink - I don't think this deserves a response, it's a weak attack that furthers nothing. I won't waste my time on it.

> Ensuring uniform randomness is not free, and comes at a cost of slower runtime, non-deterministic runtime

Given how it's used here, can you show that there's a problem? With how it's used, the performance difference would be trivial at best - though I would welcome a real-world scenario where it actually matters. 

----

OK, so now that I'm through all of that:

1. This is easy to 'fix' to make it uniform, or reasonably so. - at basically no additional cost over the existing implementation. So, if a change is going to be made, improve it.
2. This isn't really a security issue, not really a performance issue, for that matter I wouldn't really call it an issue.
3. I'd call it wontfix and be done.

**Comment by sdrapkin** [comment]
@paragonie-scott : I never accused anyone of anything. For the record, I don't care one bit who @jedisct1 is or what he created - I only care about rational arguments. Let's not have a who-did-what 'measuring' contest. @jedisct1 was humble enough to caution that he doesn't know much about .NET/c#. Well, I do. There is absolutely no need to use any external library for CSRNG in .NET. Statements like "having libsodium provide the RNG" are evidence that you have no idea how libsodium handles CSRNG (hint: the .Windows target uses the same RtlGenRandom() that RNGCryptoServiceProvider does). Using anything other than RNGCryptoServiceProvider in .NET is, in fact, "rolling your own crypto". My tone is not *really* necessary, you are right. The proper tone should likely be a lot harsher - similar to Mr. Berstein's tone when he responds to irrational or FUD statements (read some of his papers), but I'm a nice guy.

@adamcaudill I have no clue where you got the idea that I suggested implementing an RNG, when in fact I advocate the exact opposite: ie. using the RNGCryptoServiceProvider. My suggested code snippet above also makes it crystal clear.

"Using Path.GetRandomFileName() is just as external as something from libsodium from a risk perspective - though using something from libsodium may present less of a risk thanks to the ease of auditing". I disagree completely. .NET framework has been audited, time-tested and mass-deployed (ie. attacked) a lot more than nacl, libsodium, and libsodium-net combined. Its source code is open.

Also, which part of StreamCryptor's "Requirements: targets .NET 4.5" did I miss? I didn't see "must use libsodium dependency to the maximum extent possible" in this project's description. My interpretation of "targets .NET 4.5" is using .NET 4.5 first and foremost, and only deferring to external libs for crucial unavailable functionality.

If it's a bad practice to continue replying in already-closed issues, I apologize.
